
env:
  seed: 42
  name: WorkflowScheduling-v3
  traffic_pattern: CONSTANT

  gamma: Null  # Deadline factor for initialize env
  gamma_train: 5.0   # Deadline factor for training
  gamma_test: 1.0   # Deadline factor for testing during training or after the completed training
  dynamic_gamma: False   # Default: false
  dynamic_gamma_wf: False   # Default: false

  wf_size: S
  dataGen: 500000  # How many generations to iterate: the length of generative training dataset, usually >> generation for reproducible
  wf_num: 30  # The number of workflow in each training problem instance
  evalNum: 1  # How many problem instances are used to evaluate each individual in training process. Default: 1
  wf_num_test: 30  # The number of workflow in each testing instance
  validNum: 30  # How many problem instances are used to verify the performance in testing process

  generateWay: rotation  # Default: rotation

policy:
  name: model_workflow
  state_num: 8  # will double-check in builder.py
  action_num: 1  # will double-check in builder.py
  discrete_action: True  # will double-check in builder.py
  add_gru: False
  greedy_action: False  # True (greedy in ES) or False (sampling in PG)

optim:
  name: es_openai
  population_size: 40
  maximization: True
  generation_num: 2000
  input_running_mean_std: True
  input_clip: False
  input_clip_value_min: Null
  input_clip_value_max: Null
  reward_shaping: True
  reward_norm: False
  sigma_init: 0.05
  sigma_decay: 1.0
  learning_rate: 0.001
  learning_rate_decay: 0.9999
  reinforce_learning_rate: 0.001
  weight_decay: 0.0
